### ISSUE TITLE
Bold system setting support?

### ISSUE THREAD

**Issue by AccuPhoenix01** [Mindgrub/Swash#3]
Do you think  you will add support to gracefully handle `isBoldTextEnabled` or `boldTextStatusDidChangeNotification`? So we can map SomeFontRegular to SomeFontSemiBold or SomeFontBold

BTW Swash looks awesome. Going to try it in our app soon.

**Comment by SamHFrancis** [comment]
Thanks! And sorry for the delayed response. I think this is a great idea. I've implemented it in #4. What do you think of it?

**Comment by AccuPhoenix01** [comment]
Looks good, easy to understand. I like it!
No worries, I was not in a big hurry.

One unrelated thing, in the project file, the `Targets` iOS Example > `General` > `Frameworks, Libs, Embedded Content` has the Swash.framework set to `Do not embed` but it should be set to `embed and sign` or the app has weird problems (took me a while to figure the issue). Maybe put a note in the readme if you  can't adjust it.

**Comment by SamHFrancis** [comment]
Great, I'll go ahead and merge it in!

And thanks for letting me know about that issue. I have some more general project updates I'll be pushing soon. I'll throw that in along with them.
