### ISSUE TITLE
Font sizes spreadsheet

### ISSUE THREAD

**Issue by AccuPhoenix01** [Mindgrub/Swash#5]
Hi Sam, do you have a spreadsheet of the iOS font sizes for each style? Apple does not appear to have it on their site, or its hard to find. I like the graphs on your blog about Swash, easy to understand! But would be helpful to know all the size ramps, if I override a font size that I can know how each size goes up.
This page has a link but it doesn't seem to exist there at the destination. `https://developer.apple.com/design/human-interface-guidelines/watchos/visual-design/typography/`
Thank you.

**Comment by SamHFrancis** [comment]
Hi Chris, I don't think these size ramps are documented anywhere. I got them by running an app with the Accessibility Inspector and changing the text size settings. You can override `traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?)` like the sample app does and print the values as you change the setting. Something like this, maybe with better formatting:

```
let defaultSizes: [UIFont.TextStyle: CGFloat] =
[.caption2: 11,
 .caption1: 12,
 .footnote: 13,
 .subheadline: 15,
 .callout: 16,
 .body: 17,
 .headline: 17,
 .title3: 20,
 .title2: 22,
 .title1: 28,
 .largeTitle: 34]

for (textStyle, defaultSize) in defaultSizes {
    let size = UIFontMetrics(forTextStyle: textStyle)
        .scaledValue(for: defaultSize)

    print(traitCollection.preferredContentSizeCategory, textStyle, size)
}
```

I made a spreadsheet for two text styles just for the blog post, but I don't have it on me right now. Also bear in mind that these values are subject to change with new versions of iOS.

**Comment by SamHFrancis** [comment]
Okay, I had some time so I made a table. I found that `.scaledValue(for:)` may return a decimal, while `.scaledFont(for:)` returns a font which always has a whole number for `pointSize`. Here are the values I got for iOS using the default sizes from the HIG. These would be different for watchOS and tvOS.

| | Caption2 | Caption1 | Footnote | Subheadline | Callout | Body | Headline | Title3 | Title2 | Title1 | Large Title |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| XS | 11 | 10 | 12 | 12 | 14 | 15 | 15 | 18 | 19 | 26 | 32 |
| S | 11 | 10 | 12 | 14 | 14 | 15 | 15 | 18 | 20 | 26 | 32 |
| M | 11 | 10 | 12 | 14 | 15 | 16 | 16 | 19 | 20 | 27 | 33 |
| **L (Default)** | **11** | **12** | **13** | **15** | **16** | **17** | **17** | **20** | **22** | **28** | **34** |
| XL | 15 | 14 | 14 | 17 | 18 | 19 | 19 | 22 | 24 | 30 | 36 |
| XXL | 17 | 16 | 16 | 18 | 19 | 20 | 20 | 24 | 25 | 31 | 38 |
| XXXL | 19 | 17 | 17 | 20 | 21 | 22 | 22 | 26 | 27 | 34 | 40 |
| AccessibilityM | 21 | 20 | 21 | 23 | 24 | 26 | 26 | 30 | 32 | 38 | 43 |
| AccessibilityL | 25 | 24 | 24 | 27 | 30 | 31 | 31 | 35 | 37 | 42 | 47 |
| AccessibilityXL | 30 | 29 | 29 | 32 | 35 | 37 | 37 | 41 | 41 | 47 | 51 |
| AccessibilityXXL | 35 | 33 | 33 | 38 | 40 | 43 | 39 | 46 | 46 | 50 | 55 |
| AccessibilityXXXL | 41 | 38 | 38 | 44 | 46 | 48 | 48 | 52 | 52 | 56 | 58 |

**Comment by AccuPhoenix01** [comment]
Thanks Sam, I hadn't seen you made this. I pulled the values from Apple's website and made this:
[iOSAccessibilityFontSizing.pdf](https://github.com/Mindgrub/Swash/files/4355064/iOSAccessibilityFontSizing.pdf)

**Comment by SamHFrancis** [comment]
Oh, cool! That's a nice reference, thanks. It looks like the system font values in the HIG differ slightly from those produced by `UIFontMetrics`, so that's good to be aware of.
